### ISSUE TITLE
Question about why we need to redirect the output to files

### ISSUE THREAD

**Issue by Neo-Outis** [jovanbulck/sgx-step#25]
Hi,

I have been using sgx-step for half a year, and this tool could really help us understand how sgx and related attacks work. And I'm very curious about why we have to redirect our output to an extra file ?

For example, when I was running bench, I got good result when redirecting the output to out.txt but sometimes got a bad result(miss some string accesses) if I print the result directly to the terminal. 

I know that printing things to the terminal will reduce the accuracy of attack result, but why ? Is this because printing things to terminal cost more cycles then writing things to a file and the longer cycles influence the accuracy of single-step ?

BTW, I remembered that you mentioned this phenomenon somewhere, but now I can't find it. If you still remember where you mentioned it, it will be very helpful.

Thanks for your help.

regards
Neo

**Comment by jovanbulck** [comment]
Hi Neo,

Glad to hear you are using SGX-Step and find it helpful! :-)

> And I'm very curious about why we have to redirect our output to an extra file ?

When printing to a file, the code in between two interrupts is more minimal as only the file needs to be updated (which most likely can all proceed in memory and doesn't even need to involve disk I/O). On the contrary, when writing terminal output to the screen, the kernel will have to execute more code for I/O operations etc. Hence, my hypothesis is that in the first case, where less code is executed, the caches etc remain warm, which makes the interrupt return path `ERESUME` more predictable and hence the single-stepping interval timer will fire more accurately.

I remember this was mostly important for me in early SGX-Step versions, but since I have also seen reliable single-stepping with direct terminal I/O. Also, there might be a difference depending on whether you execute the code locally on your system (ie directly update the screen) or remotely (ie send terminal output via SSH). I never really bothered to look deeper into this, but I expect that some more explicit experimentation would be able to more accurately benchmark the impact on single-stepping.

> BTW, I remembered that you mentioned this phenomenon somewhere, but now I can't find it. If you still remember where you mentioned it, it will be very helpful.

I mentioned it once in the `bench` code when initially developing the framework. This code is still from the original 1.0 release and I hope to find some time soon to refactor and integrate this all a bit cleaner and more consistent.

https://github.com/jovanbulck/sgx-step/blob/master/app/bench/main.c#L143

**Comment by Neo-Outis** [comment]
Hi ,

Thanks for your explanation !
I will conduct experiments on it.

regards
Neo
