### ISSUE TITLE
Error while running sgx-step/app/foreshadow attack.

### ISSUE THREAD

**Issue by kuldeeps5** [jovanbulck/sgx-step#36]
I did all the necessary steps present at [https://github.com/jovanbulck/sgx-step/issues/24] for running the foreshadow app. 

1. When i set 'LD_LIBRARY_PATH=/opt/intel/sgxsdk/lib64/ ldd ./app' to this i am getting this error when executing ./app 

<img width="891" alt="Screenshot 2021-01-17 at 22 12 40" src="https://user-images.githubusercontent.com/49794171/104849737-59275c80-5911-11eb-8228-916930f769c6.png">

2. When i set 'LD_LIBRARY_PATH=/usr/lib/ ldd ./app' to this i am getting this error when executing ./app :

<img width="880" alt="Screenshot 2021-01-17 at 22 13 12" src="https://user-images.githubusercontent.com/49794171/104849743-604e6a80-5911-11eb-8f82-f62ed6933771.png">

In both the cases i am not able to run ./app. What should i do to resolve this issue ?
Also i ran Sample codes present in this : sdk/intel-sdk/linux-sgx/SampleCode/ and i am able to run it.

**Comment by jovanbulck** [comment]
hm, this seems to be not an issue with SGX-Step, but with your SGX-SDK installation somehow. The 0x4004 error code indicates a problem with acquiring the launch token upon enclave creation:

`SGX_ERROR_SERVICE_INVALID_PRIVILEGE = SGX_MK_ERROR(0x4004),   /* Enclave has no privilege to get launch token */`

https://github.com/intel/linux-sgx/blob/d10c025eb0bfe0c53e524a486f2d17307d0f1206/common/inc/sgx_error.h#L83

Not sure why you get that error exactly though. Especially since you say it works for `sdk/intel-sdk/linux-sgx/SampleCode/`. Some attention points:

* If you need `LD_LIBRARY_PATH`, you should also pass it to the invocation of `./app` (nut just ldd above, it just prints stuff but does not set anything), so not sure which version of the SDK you're using exactly here.
* You'll also need to pass `sudo` before `./app`, but that'll only be a problem after you created the enclave and you'll start the page-table manipulations normally.
* you should inspect the kernel output using `dmesg` to see if there's any errors printed in there.

Crucial for current SGX-Step to work is to use the SDK and SGX driver that are in the git submodules, so you should check you don't have another incompatible SGX driver by accident. Specifically, I think the `/dev/sgx_enclave` driver has recently been upstreamed to the Linux kernel, but I didn't update SGX-Step so you should make sure you don't have that driver and are using the `dev/isgx` one.

Sorry for the delayed answer, lost track, hope this still helps!

**Comment by jovanbulck** [comment]
issue seems dead, so closing
