### ISSUE TITLE
Hyperlink of the approach to bypass devmem_is_allowed checks is unavailable

### ISSUE THREAD

**Issue by xiaonan-INTC** [jovanbulck/sgx-step#42]
In README.md:
Building and running 
1. Build and load /dev/sgx-step
approach: https://www.libcrack.so/2012/09/02/bypassing-devmem_is_allowed-with-kprobes/

This hyperlink shows: 
404: Page Not Found

So how to solve the issue of preventing /dev/mem?

**Comment by xiaonan-INTC** [comment]
Thanks for the reply, jovanbulck. :). 
But here is still an error as below, do you have solution for it?

/home/sgx-step/kernel/linux-sgx-driver/sgx_page_cache.c: In function ‘sgx_swap_pages’:
/home/sgx-step/kernel/linux-sgx-driver/sgx_page_cache.c:379:23: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  down_read(&encl->mm->mmap_sem);
                       ^~~~~~~~
                       mmap_base
/home/sgx-step/kernel/linux-sgx-driver/sgx_page_cache.c:382:21: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  up_read(&encl->mm->mmap_sem);
                     ^~~~~~~~
                     mmap_base
make[2]: *** [scripts/Makefile.build:271: /home/sgx-step/kernel/linux-sgx-driver/sgx_page_cache.o] Error 1
make[1]: *** [Makefile:1851: /home/sgx-step/kernel/linux-sgx-driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.14.0-aex'
make: *** [Makefile:16: default] Error 2

**Comment by jovanbulck** [comment]
This seems to be an issue in the linux-sgx-driver. Currently, SGX-Step uses v2.11 that is not compatible with newer Linux kernels. This has been fixed in v2.14 and I pushed commits to SGX-Step to use the latest version v2.14 of the driver (plus also the latest linux-sgx SDK v2.16).

This should fix your issue hopefully. Let me know (by opening a new issue) if problems remain!
