### ISSUE TITLE
/dev/sgx-step would be uninstalled after os reboot

### ISSUE THREAD

**Issue by xiaonan-INTC** [jovanbulck/sgx-step#49]
HW: NUC7JYJ
SW: Ubuntu Desktop 20.04

Reproducible steps:
1. install sgx-step following the wiki Building and Running - 0, 1, check by $ls /dev/sgx-step, OK
2. reboot os
3. check by $ls /dev/sgx-step again, NO

Is this normal?

**Comment by jovanbulck** [comment]
Yes, this is normal expected behavior. The `make load` target only loads the driver but does not "install" it to be auto-loaded on next reboot. This was a somewhat deliberate choice since `/dev/sgx-step` should only be used for experiment and not be used on a production machine as it exposes physical memory directly to user space and, hence, compromises system security altogether..

If you'd like, you can always install `/dev/sgx-step` across reboots, similar to how this is done in [`install_sgx_driver.sh`](https://github.com/jovanbulck/sgx-step/blob/master/kernel/install_SGX_driver.sh). I'd also be happy to merge a PR for a similar `make install` target or so :)

**Comment by xiaonan-INTC** [comment]
> Yes, this is normal expected behavior. The `make load` target only loads the driver but does not "install" it to be auto-loaded on next reboot. This was a somewhat deliberate choice since `/dev/sgx-step` should only be used for experiment and not be used on a production machine as it exposes physical memory directly to user space and, hence, compromises system security altogether..
> 
> If you'd like, you can always install `/dev/sgx-step` across reboots, similar to how this is done in [`install_sgx_driver.sh`](https://github.com/jovanbulck/sgx-step/blob/master/kernel/install_SGX_driver.sh). I'd also be happy to merge a PR for a similar `make install` target or so :)

Thanks a lot jovanbulck, that's clear for me! From my point current realization is completely OK. :)
