### ISSUE TITLE
Could sgx-step support SGX in-kernel/dcap driver?

### ISSUE THREAD

**Issue by xiaonan-INTC** [jovanbulck/sgx-step#53]
Hi, 

Currently sgx-step can only run with SGX oot-driver, does it have the capability to run on SGX in-kernel or dcap driver since those are the major drivers of SGX?
I tried sgx-step with SGX in-kernel/dcap driver, it failed to run...

**Comment by jovanbulck** [comment]
Hi xiaonan,

Support for the in-kernel sgx driver has recently been implemented as per #39 .

Did you make sure to pull the latest master _and_ follow the updated instructions in README (ie pass all the updated Linux cmd line params)? 

Hope this clarifies and solves your issues! If not, let me know what precisely goes wrong w
Including a detailed log of what you did and what fails and I'd be interested to fix this as the in-kernel driver should be supported on recent SGX-Step distributions.

If it is fixed by pulling the latest code and applying instructions, also let me know so this issue can be closed :)

**Comment by xiaonan-INTC** [comment]
> Hi xiaonan,
> 
> Support for the in-kernel sgx driver has recently been implemented as per #39 .
> 
> Did you make sure to pull the latest master _and_ follow the updated instructions in README (ie pass all the updated Linux cmd line params)?
> 
> Hope this clarifies and solves your issues! If not, let me know what precisely goes wrong w Including a detailed log of what you did and what fails and I'd be interested to fix this as the in-kernel driver should be supported on recent SGX-Step distributions.
> 
> If it is fixed by pulling the latest code and applying instructions, also let me know so this issue can be closed :)

Thanks @jovanbulck , 
I pull latest sgx-step code and it works with In-kernel driver!
