### ISSUE TITLE
./install_SGX_SDK.sh can't find python2

### ISSUE THREAD

**Issue by kmarzouq** [jovanbulck/sgx-step#61]
Trying to run ./install_SGX_SDK.sh but it says "E: Unable to locate package python2". I checked and I do have python 2.7 installed in "/usr/bin/python2". I removed "python2"  from the installing prequisites part of ./install_SGX_SDK.sh and it ran, even saying that the SDK was successfully installed, but testing it out with the commands "cd app/idt" and then "make run", it gives the error " assertion '(fd_step = open("/dev/sgx-step", O_RDWR)) >= 0' failed: No such file or directory"

**Comment by jovanbulck** [comment]
splitting, bc there's 2 separate issues here:

> Trying to run ./install_SGX_SDK.sh but it says "E: Unable to locate package python2". I checked and I do have python 2.7 installed in "/usr/bin/python2". 

okay, thanks for the catch! This is probably because of the older SDK version. I should rebase the SGX-Step patches later to work with the latest SDK 2.19 which moved to python3 I think. Can you clarify: on which version of ubuntu was this (`lsb_release -a` should tell you)?

> it gives the error " assertion '(fd_step = open("/dev/sgx-step", O_RDWR)) >= 0' failed: No such file or directory"

this means you didn't load the /dev/sgx-step driver (you should do this after every reboot)

**Comment by kmarzouq** [comment]
The version of Ubuntu I am using 18.04 LTS.

**Comment by jovanbulck** [comment]
I'm closing this as the SDKs are now rebased to lastest version, which does not have Python issues anymore + Ubuntu 18.04 is no long officially supported (CI tests run on both Ubuntu 20.04 and Ubuntu 22.04 so those should always work normally)
